### ISSUE TITLE
Research agent based modelling to choose journeys

### ISSUE THREAD

**Issue by jwestw** [jwestw/Public_Transport_Efficiency#31]
See the description of [the problem](https://github.com/jwestw/Public_Transport_Efficiency/milestone/3). 

In a previous meeting with DSC, we spoke about how to select journeys in cities and the suggestion of "agent based modelling" came up. 

Apparently, in ONS, Ian Benedikt is working on something related to this. 

**Tasks:**

- [ ] Read up on agent based modelling.
     - [ ] https://www.sciencedirect.com/science/article/pii/S1877050918304435
     - [ ] https://en.wikibooks.org/wiki/Fundamentals_of_Transportation/Agent-based_Modeling
- [ ] Keep notes on research and how this might be applicable to our problem
- [ ] Contact Ian (email address available from me) to discuss.
