### ISSUE TITLE
Look into OpenRouteService features

### ISSUE THREAD

**Issue by jwestw** [jwestw/Public_Transport_Efficiency#34]
**Tasks:**
- [ ]  Go to [OpenRouteService](https://openrouteservice.org/) and take notes on their features. 
- [ ] If they are useful, apply for a governmental "Collaborative" [plan](https://openrouteservice.org/plans/)
- [ ] Make a comparison (table?) between this and Traveltime API and even Open Trip Planner.

If we set this up, how do travel times vary between OpenRouteService and Traveltime API

**Comment by chloemurrell** [comment]
### *Comparison of features*
| TravelTime       | OpenRouteService | 
|--------------------------|--------------|
| Time-Distance Matrix | Time-Distance Matrix  | 
| API Limit - 1000 credits per month, 10 credits per minute  | API Limit (Matrix) - 500 daily / 40 per minute |
|  Specific public transport mode  | Modes of transport - Cycling, walking, car, bus/heavy vehicle/ delivery truck [Options within maps](https://maps.openrouteservice.org/#/place/@8.76709,49.510944,10). I don't think it includes public transport? [Restrictions](https://openrouteservice.org/restrictions/)|

**Comment by jwestw** [comment]
@penbet This is an open ended ticket. Please take a look.
